### ISSUE TITLE
Closing HTTP cleanly (the return)

### ISSUE THREAD

**Issue by tlienart** [asprionj/LiveServer.jl#10]
It's funny, I was writing a MWE to post on HTTP.jl about how you can't really shut down their listener and wrote this:

```julia
using HTTP
using Sockets
server = Sockets.listen(8000)
@async HTTP.listen(ip"127.0.0.1", server=server) do http::HTTP.Stream
    if http.message.method == "GET" && http.message.target in ("/", "/index.html")
         h = HTTP.Handlers.RequestHandlerFunction() do req::HTTP.Request
                 HTTP.Response(200,read("index.html", String))
             end
         HTTP.Handlers.handle(h, http)
    end
end
try
    while true
        sleep(0.1)
    end
catch err
    isa(err, InterruptException) && close(server)
end
```

However this works... perfectly fine!

So I think the problem is to do with websockets still remaining active... Using `close(wsi.io)` may not kill the websocket completely (not sure what happens), using `close(wsi)` sometimes doesn't work depending on the status and may throw an error (at least when I tried).

Anyway this is not really an issue but if you have a better understanding for what's going on, it might help us improve that part of the code (which currently works but is a bit ugly)

**Comment by tlienart** [comment]
Ok after much head scratching and some thinking, I think it's actually a bug in HTTP.jl which launches many `@async` loops and therefore some of the connection handlers may in fact be unaware that the server has been closed.

I modified their code adding explicit references to the server and it fixes the problem. This is discussed on the HTTP.jl repo, hopefully I'll get some feedback there and we can move on here.

**Comment by asprionj** [comment]
The problem really seems to be with HTTP.jl, see my very-minimal example (without websockets etc.) in issue 405. So we keep this issue here open until it is fixed in HTTP.jl.

**Comment by tlienart** [comment]
So I think it will take time before HTTP.jl gets fixed properly as they're not keen on my simple (but not ideal)  patch of making the whole stack aware of the status of `server`.

Given that I expect it will take them quite a while before they fix this and it would be nice for us to not have this bug, I changed  the Manifest.toml to reflect the fact that we want my branch of HTTP.jl. I'll add this in the doc and we will fix it eventually when HTTP.jl fixes their bug.

**Comment by asprionj** [comment]
Agreed.
