### ISSUE TITLE
Allow serve single file

### ISSUE THREAD

**Issue by Moelf** [asprionj/LiveServer.jl#108]
using this with `Weave.jl`. Usually PDF readers are able to auto-refresh. But for browsers, due to security, extensions are not allowed to read `file://`. Currently I need to make a `ln blah.html index.html` for LiveServer to work.

I think this is already possible if we manually make a `filewatcher` or something, so maybe just document how to DIY this would be enough.

**Comment by tlienart** [comment]
Hello, sorry I'm unclear on what you're trying to do. If you have a file `blah.html` with 

```html
<html>
	<body>
		<h1>Hello</h1>
		This is some more text.
	</body>
</html>
```

and you do 

```
using LiveServer; serve()
```

and navigate to `localhost:8000/blah.html` it will be live rendered; no need for it to have the name `index.html` ? 

Could you clarify what you're hoping to do + provide a MWE? thanks!

**Comment by Moelf** [comment]
oh you're absolutely right and I was not thinking.
