### ISSUE TITLE
Good interface for file watchers

### ISSUE THREAD

**Issue by asprionj** [asprionj/LiveServer.jl#12]
We need to define a clean and suitable interface for file watchers. (In the context of branch `simpleFW`).

One idea that just came to my mind is to require them to provide methods like `add_file` (simple to do, just pass the string to the corresponding channel) and something like `set_filechange_callback`. The latter needs some thought. The idea behind it is to hide the details on the communication. That is, the "user" of the watcher (here it's the `serve()` command) should not need to know how it has to communicate (via channels in the `SimpleWatcher`, but probably differently for other watchers) but just call API methods that are always the same.

**Comment by asprionj** [comment]
Hey, have a look at [this Gist](https://gist.github.com/asprionj/fe9eddf0c30a75e6226fe2dd53970912). It is a skeleton in that it does no actual file watching, but everything around this task. It has:

- A single asynchronous task (watching the files) which terminates normally upon receving an `InterrupException` -- this is used to stop it (via `schedule`)
- No channels
- A minimal API (`start`, `stop`, `set_callback`, and in the future something like `watch_file`)

This could be a good default file-watcher for LiveServer?

**Comment by asprionj** [comment]
Ok, how would we integrate other file watchers then? They would be defined outside the package / module. I guess they'd have to overload the API methods?

**Comment by asprionj** [comment]
With 4c86f08f8b32f77ad35934a8f8da70a2fb44cc3f on branch `simpleFW` it now has the solution from the above Gist. Works fine, apart from the issues with HTTP.jl not really closing, cf. #10. Will work on a minimal example to add an own file watcher.

**Comment by tlienart** [comment]
Nice!

Some notes:

* around line 20 you catch error and then handle Interrupt, you probably want to throw anything else to be safe
* `_waitfor_task_shutdown` would be more readable on multiple lines
* types with Functions are probably not the most efficient but given that there would be only one of those I think it's likely fine

**Comment by tlienart** [comment]
PS: maybe do a PR with `simpleFW` and I can do a proper review there?

**Comment by asprionj** [comment]
Discussion / code review to be continued in #14. I think it's a good idea to have this as the new master to build on it.
