### ISSUE TITLE
WS connection dropped on Safari

### ISSUE THREAD

**Issue by tlienart** [asprionj/LiveServer.jl#13]
So on Safari there seems to be issues with how websocket connections are handled. 

* On branch simpleFW the updates don't seem to trigger a reload
* On branch wshandling-wip the updates cause an error (stream unavailable)

The same code works on Firefox.

**Comment by asprionj** [comment]
You can check this in the browser. You can manually try to open a WS connection to the LiveServer (using the code-line from the code snippet). Probably there's some error or the resulting WebSocket object has value 3 on field `readyState`, which means "closed or did not open at all". This is what happens in Chrome/Chromium...

**Comment by tlienart** [comment]
this goes away with the fix for issue #405 in HTTP.jl so will close here.
