### ISSUE TITLE
Stop server if file-watching task fails

### ISSUE THREAD

**Issue by asprionj** [asprionj/LiveServer.jl#15]
When the file-watching task (function `_file_watcher` in the `SimpleWatcher`) fails due to an exception (not being an `InterrupException`), the server should stop. We could add an API function / a field to `SimpleWatcher` like `status` and check on this in the main loop in `serve()` that catches user interrupts. Good idea?

**Comment by tlienart** [comment]
So if I understand you correctly you want that whoever implements their own watcher side makes sure that if they catch an error, they propagate it in the form of a `Watcher.status` which should default to `runnable` and could be set to `failed` or something & can be checked upon by the main loop?

I think the problem with that is that the cause of the error is not propagated. 

I would be in favour of: 

* having the Watcher have access to the server variable
* if the server fails, the watcher stops
* if the watcher fails, it closes the server and subsequently throws an error

**Comment by asprionj** [comment]
IMO this narrows the usability of `SimpleWatcher` (and any other file watcher) for application within a server (or even exactly `LiveServer`). `status` could also be named `error` and either be `nothing` (everything is ok) or an actual catched exception. The server (or whatever uses the file watcher) could then just check for this and then throw the error after shutting down itself.

**Comment by asprionj** [comment]
I don't like them, because
> IMO this narrows the usability of SimpleWatcher (and any other file watcher implementing the same API) for application within a server (or even exactly LiveServer).

The file watcher could have a field (or even an API function returning this field, to keep the API generic) that is `nothing` if everything's fine. If an error happens, it stores (returns) this error. In this case, the server can safely shut down and then throw this error.

**Comment by tlienart** [comment]
Sounds good! I'll check the PR  out ;)

**Comment by tlienart** [comment]
Ok I think I've now done this

1. replace `@warn` by `@error`
1. set a `isok` field in the file watcher to false
1. return something so that the thread is effectively stopped
1. in the main loop in `serve`, check if `isok` otherwise throw an interrupt exception and shut everything down.

**Comment by asprionj** [comment]
Looks good for now. Whenever we may feel so, we could store the error from the watcher somewhere to make it accessible to the user (or re-throw it after everything shut down).
