### ISSUE TITLE
Controlling verbosity

### ISSUE THREAD

**Issue by asprionj** [asprionj/LiveServer.jl#16]
There needs to be a way for the user to control the verbosity of the server and file watcher. Like a print level for numerical solvers or something. Implementation could be a global `const VERBOSE = Ref{Bool}(true)` which may be toggled by a function.
Have to make sure that this also works with custom file watchers, not only with the `SimpleWatcher` defined within LiveServer.

**Comment by tlienart** [comment]
I've added this, if people implement a file watcher they would just use `LiveServer.VERBOSE.x` so it's fine.
