### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by asprionj** [asprionj/LiveServer.jl#17]
We need it. I'd suggest to go the default route with Documenter.jl and DocStringExtensions.jl for auto-documenting fields of structs etc. Any other suggestions?
Where could we host the docs? (Maybe there's also a "default" for that, but I'm not aware of it...)

**Comment by tlienart** [comment]
The default is to host on Github :) I can get this started and we can the fill jointly

**Comment by tlienart** [comment]
Done, you just need to enable the hosting as per #19 and then we need to fill it :)
