### ISSUE TITLE
Allow Documenter to write to GitHub

### ISSUE THREAD

**Issue by tlienart** [asprionj/LiveServer.jl#20]
If you could please follow the steps here:

https://juliadocs.github.io/Documenter.jl/latest/man/hosting/ 

Then Documenter will be able to push to the github gh-pages branch allowing the documentation to be hosted.

**Comment by asprionj** [comment]
Will do this ASAP, takes some time which I right now don't have (need sleep ;-)).

**Comment by asprionj** [comment]
We're up and running: https://asprionj.github.io/LiveServer.jl/dev/

**Comment by tlienart** [comment]
Great!
