### ISSUE TITLE
Minor code cleanup

### ISSUE THREAD

**Issue by tlienart** [asprionj/LiveServer.jl#21]
(I can do this after pushing some tests)

* use same docstrings everywhere. Since pretty much everything is internal, I don't think it's very useful to add [INTERNAL]
* use `!` consistently, if it mutates the object, add one (e.g. `watch_file`)
* use standardised spacing convention `arg1, arg2, arg3`
* (ongoing)

**Comment by asprionj** [comment]
Most of the above should be addressed by https://github.com/asprionj/LiveServer.jl/commit/e77e3281f1581dc57bc87c3ff824df45e5673c5c; feel free to double-check...

**Comment by tlienart** [comment]
Lol yeah I did 😉
