### ISSUE TITLE
Move API description of file watcher to doc proper

### ISSUE THREAD

**Issue by tlienart** [asprionj/LiveServer.jl#24]
We don't want to be like HTTP and have no readable doc but big docstrings everywhere ;-)

**Comment by tlienart** [comment]
Another thing is that it's not `SimpleWatcher` that people should implement but rather something `<: FileWatcher`, I've modified the code to reflect this, the doc should need to follow this. Basically it should be

```julia
mutable struct MyNewFileWatcher <: FileWatcher
# fields
end
```

**Comment by asprionj** [comment]
`FileWatcher` is probably a bad choice since there's already the very similar stdlib `FileWatching`...?

**Comment by tlienart** [comment]
Hmm you're right, though if someone wants to extend it they would have to explicitly write

```julia
mutable struct MyNewFileWatcher <: LiveServer.FileWatcher
# fields
end
```

because we don't export `FileWatcher` (so my previous comment was not complete). Of course the user could do `using LiveServer: FileWatcher` but I feel then the intent is pretty clear. Doing `... <: LiveServer.FileWatcher` would make it sufficiently different from `FileWatching` I would think?

**Comment by asprionj** [comment]
You're right.
