### ISSUE TITLE
Exported functions

### ISSUE THREAD

**Issue by tlienart** [asprionj/LiveServer.jl#27]
I don't think we need to export `start/stop/SimpleWatcher/set_callback!/watch_file!` and would think it's best we did not.

Most of the time the user will not provide a watcher. And even if they do, they should use `LiveServer....` because it's clearer what they're doing to extend the functions. (Just like when one tries to extend `Base.show` for instance).

**Comment by tlienart** [comment]
(I modified this, if you think it's a bad idea and we should export those, let's discuss here and I can fix it)

**Comment by asprionj** [comment]
Ok. We just have to precisely document, along with a simple example, how to implement a custom `FileWatcher` (or modify the provided one).
