### ISSUE TITLE
Add AppVeyor CI

### ISSUE THREAD

**Issue by tlienart** [asprionj/LiveServer.jl#29]
@asprionj can you sign into https://ci.appveyor.com/projects and add the project? I don't think anything else needs to be done, I'll add the corresponding yml file.

**Comment by asprionj** [comment]
Appveyor App is now installed for LiverServer.jl

**Comment by tlienart** [comment]
Can you check what the exact URL is for it? I can't seem to access https://ci.appveyor.com/project/asprionj/LiveServer-jl cheers

**Comment by asprionj** [comment]
Tried to add LiveServer as an Appveyor project two days ago, and right now. When clicking the `(+) ADD` button, I always get:
![image](https://user-images.githubusercontent.com/13935112/55682114-fb3da680-592e-11e9-8547-3de2ae0b01bb.png)

**Comment by asprionj** [comment]
Submitted a ticket to appveyor support...

**Comment by tlienart** [comment]
dayum windows...

**Comment by asprionj** [comment]
They just answered "try again now", and magically, it worked! Built successfully on Windows!
