### ISSUE TITLE
Add package labels to help discovery

### ISSUE THREAD

**Issue by tlienart** [asprionj/LiveServer.jl#33]
In the red circle you should see something that allows you to add tags. 

Maybe things like `web server` `julia` or whatever you think (it gives suggestions as well) would be good

![Screen Shot 2019-04-05 at 6 03 43 pm](https://user-images.githubusercontent.com/10897531/55609988-c239f080-57cd-11e9-9f86-bec7279851cd.png)

**Comment by asprionj** [comment]
Done, let me know when you think there should be others or modify these ones.
