### ISSUE TITLE
Move JS snippet to .js file

### ISSUE THREAD

**Issue by asprionj** [asprionj/LiveServer.jl#35]
Then read this into memory (e.g. when starting the server). Keeping it as a string in a .jl file just isn't the right way to do it.

**Comment by asprionj** [comment]
I saw that you moved the entire `<script>` tag the file, renaming it to `.html`. This also was my initial idea. I then went for the `.js` solution, wrapping it a `<script>` tag by `serve()` because we actually only care about the JS-code. Like this, we could just reference this .js-file in the HTML `<script>` tag as `src`, or add an AJAX request to the HTML files that fetches and runs this script file. Just as we see fit in the future.

But then again, we can still change it back if we come to this point in the future; so keep it as it is (`.html`) for now.

**Comment by tlienart** [comment]
Ok yes, either way is fine and I understand that we may change it back to `.js` as you had it. I think I was less keen at having `BROWSER_RELOAD_SCRIPT` being a `Ref` it felt a bit unnecessary. 

Ok for changing this in the future if we want to do something like you said.
