### ISSUE TITLE
WebSocket handler to keep connection alive

### ISSUE THREAD

**Issue by asprionj** [asprionj/LiveServer.jl#36]
The issue with Chromium in #2 seems not to originate in insecure connection to `localhost`. I added an `onopen` method to the WebSocket object in the client, `console.log`-ing some text. Also, added a `console.log` to the `onmessage` method, and made `ws_tracker` send a welcome message to the client right at the end, just before `return nothing`. Both messages are shown also in Chromium. That is, the connection opens and also successfully receives the message, but then instantly closes.

I then added a `sleep(10)` just before the `return nothing` at the end of `ws_tracker`. In Chromium, the websocket now remains open (`readyState` 1) for 10 seconds, then closes. Can also be nicely observed using `verbose=true` in `HTTP.listen`. So, I guess that:

- Once the handler function passed to `HTTP.listen` returns, the `HTTP.Stream` is closed.
- The unintended behavior is probably with Firefox, not with Chromium. Chromium closes the connection as it should, but Firefox somehow keeps it alive, even though the server seems to close it...? (No idea how this is possible at all...!)

So, does this mean that we need to have another async task for each WS connection? I assumed this (keeping the stream open, closing it once the websocket is closed) would be handled internally by HTTP.jl's `WebSocket` type.

**Comment by asprionj** [comment]
Ok, HTTP.jl already runs the handler function (here: `ws_tracker`) asynchronously. It's basically here: https://github.com/JuliaWeb/HTTP.jl/blob/95b8bad768047532c8c782932a77ec026305354a/src/Servers.jl#L247-L261

L247 runs the entire `try` statement async, and L259 in the `finally` clause closes the IO-stream. I have no idea why it still worked with Firefox. Probably their `WebSocket` implementation automatically reconnects when the connection is lost without having received an explicit "close" frame.

That is, we should also have something like
```julia
while isopen(ws.io) sleep(0.05) end
```
at the end of `ws_tracker`, and a `try` construct over the entire function body. Upon error, the error is printed but everything is continued normally (i.e. the handler returns). Upon an `InterruptException` we then have to make the server stop, similar to what we do for file watching. Otherwise, the user has to press `Ctrl-C` as many times as there are open websockets, plus one last time (for the server itself).

**Comment by asprionj** [comment]
Ha, since this is `server` internal (not interacting with `file_watcher`), we can use a simple `const WS_ERROR = Base.Ref{Bool}(false)` and set this to `true` upon catching an interrupt ex in any `ws_tracker`. Tested everything, works perfectly, now also with Chrome/Chromium!

**Comment by tlienart** [comment]
Ok I played a bit with this and effectively kept as it was except that the `try` only really needs to be around the `while` thing. I also think it's super important to add this in the comments so that future contributors  (or ourselves) know why we're doing this :p. Maybe check what I've added (comments) and adjust as you feel :-)

**Comment by asprionj** [comment]
Looks good.
