### ISSUE TITLE
Check get_file works on windows, possibly replace with URI handling from HTTP

### ISSUE THREAD

**Issue by tlienart** [asprionj/LiveServer.jl#4]
The `get_file` might work fine on UNIX but I'm not sure it would on Windows given it uses different paths AFAIU. 

Also it seems some of the manipulation with paths could be done with the possibly more robust [URI machinery from HTTP.jl](https://github.com/JuliaWeb/HTTP.jl/blob/ad59dd580932688e7047a7ee226791e274b91f5f/src/URIs.jl).

**Comment by asprionj** [comment]
I wanted to use HTTP.URI stuff, but somehow forgot in the heat of coding. Should definitely do this.

**Comment by tlienart** [comment]
done in e72041b , I think eventually we can add AppVeyor tests (i.e. simulating windows env). That may well fail but might show us what's causing issues etc.
