### ISSUE TITLE
Using servedocs & kicking the tire (?)

### ISSUE THREAD

**Issue by tlienart** [asprionj/LiveServer.jl#43]
**Suggestion**: I think it's a good exercise and test for us to write the doc while using the `servedocs` function and reporting errors here, hopefully that will help us kick the tire and get rid of sneaky bugs.

```julia
julia> pwd()
/Users/tlienart/.julia/dev/LiveServer.jl
julia> using LiveServer
julia> servedocs()
```

If you modify a `md` file such as `index.md`, a pass of `Documenter.jl` is re-triggered and the changes appear in the browser. Great that's what we want. 

**A problem encountered**

It seems we can still have a problem with websocket connections being dropped. I got this one once (but couldn't reproduce...)

```julia
┌ Info: Deployment criteria:
│ - ✔ ENV["TRAVIS_REPO_SLUG"]="" occurs in repo="github.com/asprionj/LiveServer.jl.git"
│ - ✘ ENV["TRAVIS_PULL_REQUEST"]="" is "false"
│ - ✔ ENV["TRAVIS_TAG"]="" is (i) empty or (ii) a valid VersionNumber
│ - ✘ ENV["TRAVIS_BRANCH"]="" matches devbranch="master" (if tag is empty)
│ - ✘ ENV["DOCUMENTER_KEY"] exists
└ Deploying: ✘
┌ Error: An error happened whilst watching files; shutting down. Error was: Base.IOError("write: broken pipe (EPIPE)", -32)
└ @ LiveServer ~/.julia/dev/LiveServer.jl/src/file_watching.jl:113
ERROR: ┌ Error: Exception while generating log record in module LiveServer at /Users/tlienart/.julia/dev/LiveServer.jl/src/file_watching.jl:113
│   exception =
│    InterruptException:
```

Anyway I think it's great if we use that so that we can practice with it more extensively and eventually have something that works most of the time!

**Comment by asprionj** [comment]
Haha, nice idea testing something by writing the docs to it using itself...

**Comment by tlienart** [comment]
:-) I also think that this `servedocs` functionality would be very useful to people writing their docs as they would directly see the output...! (this works for any package not just for ours)

**Comment by tlienart** [comment]
Errors I got so far:

* `broken pipe` (twice, no particular action) --> we may have to do something to check if the websocket has not been unduly closed (I imagine that's what was the problem) and if it has been closed before we wanted it to, to re-open it
* a cryptic `InexactError(:check_top_bit, UInt16, 0xad22)`, this may have been caused by me moving an active tab into a separate window but should not...

**Comment by tlienart** [comment]
Ok so adding a `try` around the pinging mechanism removes that first broken pipe error.

```julia
try
            write(wsi, "update")
            close(wsi)
catch
end
```

But it still triggers reload so I'm guessing we're not purging viewers well enough. I think we should keep that try catch and check that we don't try to ping closed/closing sockets.

**Comment by asprionj** [comment]
Just an idea; wouldn't it be nice to be able to just call
```julia
servedocs(MyModule)
```
?

We could simply use
```julia
dirname(pathof(LiveServer))
```
to get the module's `src` folder, and look for `docs` in the parent directory, then pass the path to `docs` to `serve`.

**Comment by tlienart** [comment]
I'm opening this in a new issue for additional thinking
