### ISSUE TITLE
[docs] structure

### ISSUE THREAD

**Issue by tlienart** [asprionj/LiveServer.jl#44]
I saw that you added a fair bit of content to `filewatching.md` which is great however I must say I was a bit confused by it all (it gives the impression that you can use the filewatcher for things that are unrelated to the server, this may be true but I don't think it should be advertised because it's not really what it's meant for... even if it's true I think we should concentrate for now on the primary goal for the package).

I therefore think it would help if we established the structure of the different parts of the docs together?

My thoughts for the docs would have been something like:

```
. Landing page: how to quickly get it going
. Overview of how it works
  . something short that corresponds to your nice doc/drawing in #5 and links to relevant subparts of docs
. Functionalities (public API)
  . explain in more details how serve works + keywords
  . explain verbose
  . explain servedocs
  . Note: explain that there may be errors if re-starting the server in a same julia session due to a bug in HTTP
. Extending LiveServer
  . extending simplewatcher to take your own callback
  . writing your own watcher
. Libs
  . Filewatching
    . when the file changes, the time of last change is compared, trigger a callback function
    . explain that the standard callback causes the browser refresh, refer to the relevant part of the doc in `server` that explains how the websockets work
  . Server
    . a server is started at localhost:port , upon a request (url entered in browser), the relevant file is served to the client and the file is marked as being watched with a websocket corresponding to the requester
    . each watched file has a number of viewers in the form of websockets (e.g. tabs)
    . a file change will cause the server to write on all websockets associated with the file (see `update_and_close_viewers`
  . Error handling
    . explain the different errors and how they're handled/propagated
```

of course can modify etc, what do you think?

**Comment by asprionj** [comment]
Yep, that structure looks good. Didn't spend a second on thinking about the structure. Just was in the mood of writing so I just started. Feel free to re-structure what's already there into this structure.

**Comment by tlienart** [comment]
I've started this in #46, will leave open while it's ongoing
