### ISSUE TITLE
Sequence of events --> DOCS

### ISSUE THREAD

**Issue by tlienart** [asprionj/LiveServer.jl#5]
This is a possible reason behind #3 I think I need another pair of eyes on the reasoning given that this websocket and HTTP business is still a bit mysterious to me

###  sequence of events

(this is what I think happens, I think it would be useful to fine tune this and have it eventually somewhere in the doc as it's useful to understand / improve?)

1. launch of liveserver
1. initial browser event : {direct visit of server @ `ipaddr:port` OR refresh of a page that was already there}
1. triggers one or several GET request(s) to server (several in the case where the page itself loads secondary stuff like CSS); for each of these GET request
1. each request is caught by `HTTP.listen` and the corresponding `http.message` has a header that contains the "GET"
1. HTTP.handle is called, the file requested is added to the filewatcher
1. a HTTP.Response(202, ...) is returned to the browser with the content of the file requested AND the reloading script
1. an `upgrade` message is triggered after the response for that file
1. the upgrade message is then processed by the `ws_tracker`
1. a **new** websocket is launched and associated with that file and appended to a list of websockets

Then upon a file event on one of those watched files (let's assume it's a html file)

1. the file event effectively triggers a ping on all available (open/active) websockets associated with the file
1. this is effectively a message that is caught by the browser which is  looking at that websocket via the javascript `sock.onmessage`
1. this triggers a browser-reload

But then, and this is the important part

1. the browser-reload re-generates a GET request

and with it the sequence of event where basically a new websocket is added.

**Anyway**: 

1. would be good to check if this order of operations is right, possibly it's partially right but would be good to have it exactly right
1. if it's confirmed then that explains #3 since every browser reload re-triggers the construction of a new (not useful) websocket

And it seems to me we should be able to detect that? Ideally we would be able to distinguish at the GET level

* GET request coming from a new tab / new browser  ==> needs a new websocket
* GET request coming from something already active  ==> no need for a new websocket unless there is none available

What do you think and would you see a way of going about this?

**Comment by tlienart** [comment]
one possible thing to do would be to send back a message with

```javascript
.send(browser.tabs.getCurrent().id)
```

**Comment by asprionj** [comment]
_Some general points:_
A ws connection starts as a normal http request from client to server, just with some special header fields that ask for an "upgrade" of this connection to a ws connection. If the server can handle ws, it can agree to this upgrade (the "handshake"), which then establishes the connection. From then on, both sides continuously listen to and can send messages over the connection. 

---

You're right on events 1-6. But then...

> 7. an upgrade message is triggered after the response for that file

Nope, the server does not actively send anything more to the client. Rather, the code snippet added to every HTML file sent to the client opens (or, as described above, "asks for") a ws-connection to the server.

>  8. the upgrade message is then processed by the ws_tracker

`ws_tracker` just handles the upgrading of the http-request into a ws, i.e. it "creates" the ws connection, and ads it to the list of viewers of the file. Note, the ws request from the client asks for the same URI as the file the code snippet is in (cf. `WebSocket("ws://" + location.host + location.pathname`), so associating the connection to the correct file is the same as for a standard HTTP GET request for that HTML file. If we'd just use `location.host` we'd have, for example, to wait for a first message from the client telling the server which file it watches...

> 9. a new websocket is launched and associated with that file and appended to a list of websockets

You're almost right here. It should be clear by now that the server does not launch a ws, but just accepts the request from the client to establish a ws connection.

You're right on the other parts (what a file event triggers, and that this starts the entire process anew).

---

I guess you thought that a browser tab will always have a single ws connection, which is kept alive over page reloads. Now, the browser ditches the entire JS workspace (global variables, function definitions, etc.) of a page when navigating to another page -- or reloading a page. So there is, AFAIK, no way to persist a ws over page reloads.

One could achieve something like that, probably similar to https://github.com/rumkin/pill, but based on a ws connection. You'd basically have a "skeleton" page in which the actual content is completely exchanged by new content sent over the ws. However, triggering reloads of linked files (CSS, JS, pictures, ...) would then become quite complex.

Hope that helps...?

**Comment by tlienart** [comment]
Yeah that's great, I'll put that in the docs as I think it's super helpful to also generally understand how basic  HTTP and websocket works.
