### ISSUE TITLE
Tag a first release

### ISSUE THREAD

**Issue by tlienart** [asprionj/LiveServer.jl#50]
Assuming you're roughly ok with

* state of the docs rough
* using my branch of HTTP.jl for now

I think we can tag a release and try to register the package, test it a bit more, and then eventually announce it. 

In the "test it a bit more", I intend to hook it into `JuDoc` which should provide a good use case (and more tire kicking should there be any more sneaky bugs to find out).

* [Registrator.jl](https://github.com/JuliaComputing/Registrator.jl)

**Comment by asprionj** [comment]
Yep, will look over the docs ASAP. Quickly tried `servedocs` today, very nice.

**Comment by asprionj** [comment]
@tlienart, do you want to improve #51 before a first tag or let's go?

**Comment by tlienart** [comment]
good for 0.1 tag as far as I'm concerned (doc fixes can be done on the go)

That being said I think we'll have to wait a little bit before it can be registered officially because the registrator package is not yet fully live  (https://discourse.julialang.org/t/switching-package-registration-systems-soon/22677) but I think it will be within the next 24-48h. 

Finally as soon as it's tagged we'll have to be more careful about fixes and updates, not breaking the API and follow a more standard "PR - review - merge" thing (I'm definitely guilty of having done a lot of that all in one so this message is mostly for me) + follow semver.

**Comment by tlienart** [comment]
PS: if announcing before doing some work on #57, probably important to mention that it's alpha and that we expect there may still be errors thrown when the server is interrupted.

**Comment by asprionj** [comment]
Agree about alpha status and #57. The docs should be quite OK now, did a one-swipe overhaul yesterday, catching some typos, 2-3 broken links and 1-2 missing function docs. I used `servedocs()`, it's really nice to use. Added the note that only the first run of `Documenter.jl` fetches the docstrings, while the further passes do not update them. Also, I had some random "broken pipe" error once when saving a modified `.md` file.

**Comment by asprionj** [comment]
I don't fully get what's now the status on `registrator.jl`? Is it live now? We could tag+release tomorrow since it's my birthday...? ;-)

**Comment by tlienart** [comment]
Yeah it's live, meaning you can install it, and you can do @registrator tag or something like that (cf their readme). The package will not be immediately available though as it first needs to be merged into General (I don't know how this happens) e.g. https://github.com/JuliaRegistries/General/pulls 

I think even if it's not registered it could be announced tomorrow :D

**Comment by tlienart** [comment]
Ok it's fully live and things are being merged as they should so:

1. install the Registrator app for this repo: https://github.com/apps/juliaregistrar/installations/new 
2. open an issue with comment `@JuliaRegistrator register()`

Happy birthday :)

**Comment by asprionj** [comment]
Did you get the thing about package versions and git tags? (https://github.com/JuliaComputing/Registrator.jl#note-on-git-tags-and-github-releases) Specifically, where to put this `git tag` command to trigger a git tag by registering / updating the package?

**Comment by asprionj** [comment]
@JuliaRegistrator register()

**Comment by tlienart** [comment]
Yeah we're live!

**Comment by tlienart** [comment]
Ps: @asprionj maybe consider https://github.com/apps/julia-tagbot which works alongside of registrator.jl to make sure both are in synch etc.
