### ISSUE TITLE
servedocs(MyModule)?

### ISSUE THREAD

**Issue by tlienart** [asprionj/LiveServer.jl#54]
Suggestion in #43 to have

```julia
servedocs(MyModule)
```

So a few considerations:

* I'm not entirely sure the use case is relevant, wouldn't the person just do that in the right folder? My workflow is to open Atom in the MyModule.jl folder and then you'd have to `using MyModule, LiveServer; servedocs()` which doesn't seem like too much to ask especially compared to Documenter which requires basically something similar?)
* if `MyModule` is active, then this can work indeed via `dirname(pathof(MyModule))`
* if `MyModule` is not active then this will not work and then something extra needs to be done to make the module active first (`using MyModule`). 

Maybe something that could be done is a macro

```
@servedocs MyModule
```

which would

* check if MyModule is active, if not activate it
* run servedocs in the appropriate location

**Comment by asprionj** [comment]
Agreed, it's really low-prio. Like the macro version.
