### ISSUE TITLE
Error chasing

### ISSUE THREAD

**Issue by tlienart** [asprionj/LiveServer.jl#57]
So I'm now using LiveServer heavily with JuDoc while deploying new templates and 95% of the time it's all great.

A few times I've had error triggered when closing the server (upon interrupt). Here's one of the latest ones:

```
^CERROR: EOFError: read end of file
Stacktrace:
 [1] #serve#8(::Int64, ::String, ::Bool, ::getfield(JuDoc, Symbol("##92#93")){Bool,Bool,NamedTuple{(:md, :html, :other, :infra),NTuple{4,Dict{Pair{String,String},Float64}}},NamedTuple{(:head, :pg_foot, :foot),Tuple{String,String,String}}}, ::typeof(LiveServer.serve), ::LiveServer.SimpleWatcher) at /Users/tlienart/.julia/dev/LiveServer.jl/src/server.jl:234
 [2] #serve at ./none:0 [inlined] (repeats 2 times)
 [3] #serve#91(::Bool, ::Bool, ::Int64, ::Bool, ::typeof(serve)) at /Users/tlienart/.julia/dev/JuDoc/src/manager/judoc.jl:177
 [4] serve() at /Users/tlienart/.julia/dev/JuDoc/src/manager/judoc.jl:149
 [5] top-level scope at REPL[3]:1
caused by [exception 1]
EOFError: read end of file
Stacktrace:
 [1] try_yieldto(::typeof(Base.ensure_rescheduled), ::Base.RefValue{Task}) at ./event.jl:277
 [2] wait() at ./event.jl:336
 [3] wait(::Base.GenericCondition{Base.AlwaysLockedST}) at ./event.jl:99
 [4] stream_wait(::Timer, ::Base.GenericCondition{Base.AlwaysLockedST}) at ./stream.jl:47
 [5] wait at ./event.jl:456 [inlined]
 [6] sleep at ./event.jl:510 [inlined]
 [7] #serve#8(::Int64, ::String, ::Bool, ::getfield(JuDoc, Symbol("##92#93")){Bool,Bool,NamedTuple{(:md, :html, :other, :infra),NTuple{4,Dict{Pair{String,String},Float64}}},NamedTuple{(:head, :pg_foot, :foot),Tuple{String,String,String}}}, ::typeof(LiveServer.serve), ::LiveServer.SimpleWatcher) at /Users/tlienart/.julia/dev/LiveServer.jl/src/server.jl:230
 [8] #serve at ./none:0 [inlined] (repeats 2 times)
 [9] #serve#91(::Bool, ::Bool, ::Int64, ::Bool, ::typeof(serve)) at /Users/tlienart/.julia/dev/JuDoc/src/manager/judoc.jl:177
 [10] serve() at /Users/tlienart/.julia/dev/JuDoc/src/manager/judoc.jl:149
 [11] top-level scope at REPL[3]:1
```

I think what happens there is that the ordering of events is such that there's still potentially a stream being written to as part of the HTTP side which gets closed and doesn't know what to do. 
I'm not sure about this and in a way it's irrelevant bc such errors are hard to reproduce but I've seen that one, sometimes the Broken Pipe error, sometimes something else. It's rare though but just looks unclean.

My reasoning is that we should be careful when catching errors. Possibly we should allow for some errors to be left un-propagated in `LiveServer.serve()` because they will have been ultimately caused by the interruption (and so we don't care about catching it). 

Ideally we would check where the error comes from but I'm not sure how to do that (maybe backtrace?)

I'll try to build a short list of such errors that I've seen & I think we should ignore:

## reproduced

1. EOFError (reproduced above)

## not reproduced recently

1. IOError (I think doesn't happen anymore since putting the websocket update message in a try/catch) **Edit**: this does not seem to happen anymore thanks to the fix in the HTTP patch.

**Comment by asprionj** [comment]
Yep probably has to do with what you hit when pressing `Ctrl-C`. There are parts of the code that run asynchronously that do not have a try-catch, because they run quickly. Don't know if these could be an issue. When I find some time, I'll track (and write) down the entire chain what's going on for each possible action. I'll then hopefully catch all vulnerable points (and probably some other rough edges as well).

**Comment by tlienart** [comment]
Yeah that's great.

Here's another idea which can be combined with your plan: when re-throwing errors, we can wrap the errors in our own types e.g. `FileWatcherError` or `ServerError`. So instead of doing `throw(err)` we can `throw(wrap(err))`. 

This is a simple adjustment that would already allow to distinguish sources of errors (and potentially all errors in `ServerError` could be ignored while errors in `FileWatcher` would probably need to be propagated.

Anyway the idea is not very mature in my head yet but maybe something to consider?

**Comment by tlienart** [comment]
Here's a new one: `IOError, stream closed/unusable`. This is just upon clicking a link in the browser with the server running.

Note that while the error is displayed, the server still seem to function fine. This seems to have been triggered by a request that happened unexpectedly or something.

Again should probably be filtered out and ignored.

```
┌ Error: error handling request
│   exception =
│    IOError: stream is closed or unusable
│    Stacktrace:
│     [1] check_open at ./stream.jl:323 [inlined]
│     [2] uv_write_async(::Sockets.TCPSocket, ::Ptr{UInt8}, ::UInt64) at ./stream.jl:871
│     [3] uv_write(::Sockets.TCPSocket, ::Ptr{UInt8}, ::UInt64) at ./stream.jl:845
│     [4] unsafe_write(::Sockets.TCPSocket, ::Ptr{UInt8}, ::UInt64) at ./stream.jl:901
│     [5] unsafe_write at /Users/tlienart/.julia/packages/HTTP/GN0Te/src/ConnectionPool.jl:132 [inlined]
│     [6] macro expansion at ./gcutils.jl:87 [inlined]
│     [7] write at ./strings/io.jl:177 [inlined]
│     [8] writestartline(::HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}, ::HTTP.Messages.Response) at /Users/tlienart/.julia/packages/HTTP/GN0Te/src/Messages.jl:428
│     [9] writeheaders(::HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}, ::HTTP.Messages.Response) at /Users/tlienart/.julia/packages/HTTP/GN0Te/src/Messages.jl:439
│     [10] startwrite(::HTTP.Streams.Stream{HTTP.Messages.Request,HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}}) at /Users/tlienart/.julia/packages/HTTP/GN0Te/src/Streams.jl:85
│     [11] handle(::HTTP.Handlers.RequestHandlerFunction{getfield(LiveServer, Symbol("##16#21")){LiveServer.SimpleWatcher}}, ::HTTP.Streams.Stream{HTTP.Messages.Request,HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}}) at /Users/tlienart/.julia/packages/HTTP/GN0Te/src/Handlers.jl:273
│     [12] (::getfield(LiveServer, Symbol("##18#23")){HTTP.Handlers.RequestHandlerFunction{getfield(LiveServer, Symbol("##16#21")){LiveServer.SimpleWatcher}}})(::HTTP.Streams.Stream{HTTP.Messages.Request,HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}}) at /Users/tlienart/.julia/dev/LiveServer.jl/src/server.jl:213
│     [13] macro expansion at /Users/tlienart/.julia/dev/LiveServer.jl/src/http_patch.jl:115 [inlined]
│     [14] (::getfield(LiveServer, Symbol("##6#7")){getfield(LiveServer, Symbol("##18#23")){HTTP.Handlers.RequestHandlerFunction{getfield(LiveServer, Symbol("##16#21")){LiveServer.SimpleWatcher}}},HTTP.ConnectionPool.Transaction{Sockets.TCPSocket},HTTP.Servers.Server{Nothing,Sockets.TCPServer},HTTP.Streams.Stream{HTTP.Messages.Request,HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}}})() at ./task.jl:261
└ @ LiveServer ~/.julia/dev/LiveServer.jl/src/http_patch.jl:120
```

**Comment by asprionj** [comment]
I had a single random "IOError: stream is closed or unusable" (in `http_patch.jl` on line 115) once when working with `servedocs()`, right after saving a modified `.md` file (which triggers a page reload).

**Comment by tlienart** [comment]
Well there's an easy way out of that one, just comment the line 120... I don't think we care much about it.

**Comment by tlienart** [comment]
So after more usage, it seems the EOFError is the only one that pops its ugly head from time to time. Would be good to catch (and dismiss) that one.
