### ISSUE TITLE
remove the HTTP patch when HTTP#405 is fixed

### ISSUE THREAD

**Issue by tlienart** [asprionj/LiveServer.jl#59]
This takes over #48. Long story short:

* there's a bug https://github.com/JuliaWeb/HTTP.jl/issues/405 in HTTP.jl, we have a "hacky" fix for it
* to make sure people use the fix, the best way is to monkey patch and so have the code in here (see file `http_patch.jl` corresponding to the PR https://github.com/JuliaWeb/HTTP.jl/pull/406. 
* this should eventually be removed once the issue is fixed upstream

**Comment by tlienart** [comment]
done with #73

**Comment by asprionj** [comment]
Awesome, so LiveServer is now running on the official / unmodified HTTP.jl? Thanks for all the testing and updating stuff! Currently my "2 jobs" keep me busy until late...

**Comment by tlienart** [comment]
Yes! I just forgot to add the explicit requirement for >= 0.8.2 in the Project.toml, will change that now in a patch release.

Good luck for the multiple jobs ;)
