### ISSUE TITLE
Stops updating after a number of events?

### ISSUE THREAD

**Issue by tlienart** [asprionj/LiveServer.jl#6]
When running, if modifying `index.html` several times in a row (let's say ±10 times I don't think it's a precise number) the webpage seems to stop updating. (and it stops adding websockets as well).

I'm not too  sure what may cause this; will need to dig further.

**Comment by tlienart** [comment]
Ok so after much testing, I think this is basically the kind of nasty stuff that arises from using asynchronous file watcher everywhere. It's nice on paper but what happens is that there may be events that cause task switching (eg. a simple print) and it looks like file watcher may, consequently, stop watching (mark the task as done).

This is quite annoying. I will try a more bare-bones approach as in JuDoc and see if it helps. In some future we may want to get help from people who know how to use FileWatching without problems.
At the end of the day watching files is very inexpensive so we can just do that in the infinite `while-loop`, looping over all currently-watch files (which will anyway be a small number, I don't expect many websites to have hundreds of thousands of files to check, and if they do, they probably wouldn't be using live server for now ...; additionally even for that, I suspect that going through a list of hundreds of thousands of files checking the `mtime` takes of the order of the millisecond.)

**Comment by asprionj** [comment]
Since the fix to #3 I couldn't reproduce this issue. Could you check?
