### ISSUE TITLE
Announcement on discourse

### ISSUE THREAD

**Issue by tlienart** [asprionj/LiveServer.jl#62]
I guess now that we have a working 0.1.0 we should announce the package on Discourse :). 

Here are things that I think should be mentioned but of course you should be the one presenting  it  😄 

1. copy-paste the example from the readme
1. explain that it can be used combined with Documenter to have live-rendering docs when editing the docs
1. mention that it's inspired from "browser-sync"
1. that it's meant for developping sites, not for interactive apps (for that people should consider Mux and all of that stuff)
1. that we welcome comments and suggestions for improvements

Cheers!

PS: I wouldn't mention JuDoc, I want to fix a few more things before announcing that package soon. (btw, pre-rendering is working now as you suggested for KaTeX and highlight.js!!)

**Comment by asprionj** [comment]
Agreed, came up with roughly the same points. Probably can find some time this evening. JuDoc: great! Sadly, I still haven't had the time to try out all that great new stuff (the different layouts/styles etc.)... but really want to start my GH pages ASAP, have some things to share...

**Comment by asprionj** [comment]
[Look!](https://discourse.julialang.org/t/ann-liveserver-a-simple-development-server-with-live-reload-capability/23380)
