### ISSUE TITLE
SVG are not served properly

### ISSUE THREAD

**Issue by tlienart** [asprionj/LiveServer.jl#64]
This is almost certainly a problem with HTTP.jl but is causing issues here and in JuDoc. 

MWE:

```html
<!doctype html>
<html lang="en">
<body>
  <img src="blah.svg">
</body>
</html>
```

where `blah.svg` is let's say https://commons.wikimedia.org/wiki/File:Julia_prog_language.svg 

This is the result on FF (back) and Chromium (front)

![Screen Shot 2019-05-02 at 5 46 02 pm](https://user-images.githubusercontent.com/10897531/57062034-5b432500-6d02-11e9-9d2a-27392155247d.png)

Same thing with browser-sync

![Screen Shot 2019-05-02 at 5 47 50 pm](https://user-images.githubusercontent.com/10897531/57062084-7a41b700-6d02-11e9-822b-6a8e8f6247c9.png)

**with liveserver**

* works on FF
* does not work on Safari, Chrome, Chromium

**with browser-sync**

* works on FF, Safari, Chrome, Chromium (and I suspect all other major browsers)

## Working out what's going on

I'm not entirely sure what's going on but I'm 99% sure it's got something to do with HTTP.jl not sending the right MIME type or something of the sorts.

**Comment by tlienart** [comment]
This is probably relevant https://css-tricks.com/snippets/htaccess/serve-svg-correct-content-type/

There doesn't seem to be response headers being set.

Possibly we need to do this in the

```
HTTP.Response(200, content)
```

and add type `image/xml+svg`. To be continued.

**Comment by asprionj** [comment]
Hrm... again something we have to fix for HTTP.jl? :roll_eyes:
Nevermind, should be an easy fix, right? Sadly don't have any time right now...

**Comment by tlienart** [comment]
I'll ask the HTTP folks, it may be something to do with how to write the `Response` properly.
