### ISSUE TITLE
Invalid include in servedocs

### ISSUE THREAD

**Issue by fredrikekre** [asprionj/LiveServer.jl#69]
I believe this is not valid:
https://github.com/asprionj/LiveServer.jl/blob/18170d003e732402b045ca90f5ad8748a88c0aab/src/utils.jl#L77 since `make.jl` typically `using` packages that are not available from within `LiveServer.jl`.

**Comment by asprionj** [comment]
Hrm, what do you mean exactly?
>  packages that are not available from within `LiveServer.jl`

I'm not completely into the entire environments / projects stuff. When `servedocs` is invoked from a REPL using a certain environment where all the packages are available, there's no problems, are there? In what use cases could there be problems? How could these be circumvented? (Or, what would be the "correct" / clean solution?)

**Comment by fredrikekre** [comment]
> When servedocs is invoked from a REPL using a certain environment where all the packages are available, there's no problems, are there?

Yea there is. The `include` above is `LiveServer.include`, which is only allowed to load things from `LiveServer/Project.toml`. E.g. try this branch: https://github.com/fredrikekre/LiterateLive.jl/tree/fe/issue
which results in
```
julia> using LiveServer; servedocs()
┌ Warning: Package LiveServer does not have Literate in its dependencies:
│ - If you have LiveServer checked out for development and have
│   added Literate as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with LiveServer
└ Loading Literate into LiveServer from project dependency, future warnings for LiveServer are suppressed.
✓ LiveServer listening on http://localhost:8000/ ...
  (use CTRL+C to shut down)
```

> Or, what would be the "correct" / clean solution?

Not sure, three solutions:
1. Have the user input "their" include, e.g. `servedocs(f = include)`. (Pretty ugly.)
2. Make `servedocs` a macro, which could then use the `__module__` macro argument to determine the callers `include`. (Probably the most stable solution, although maybe a bit ugly with a macro).
3. Change `include` to `Main.include`. (Correct in 99% of cases or more I think, since users will call `servedocs` from the REPL)
