### ISSUE TITLE
Interruption problems on Windows 10

### ISSUE THREAD

**Issue by tlienart** [asprionj/LiveServer.jl#78]
A user reported erratic behaviour when shutting down the server while using Windows 10. 

* sometimes the server shuts down sometimes nothing happens upon pressing CTRL+C
* a fatal error thrown when trying to run the introductory example

This may or may not be related to the user's antivirus. 

If anyone (else) using windows 10 is seeing this: 

* could you please run the example in the README and report if you get an error? + do you manage to shut down the server using CTRL+C?

@ Daniel, if you could try again on your side and copy paste the full error stack trace here it could be useful too, thanks!

### tested and works ok

So far I've managed to test this on 

* Julia 1.3 + LiveServer#master + Windows server 2016 (on a VM)

(I'll add versions here to keep track of who gets it to work or not)

**Comment by asprionj** [comment]
Hi, I have Windows 8.1 at work, and Windows 10 as dual boot (but never booted it since... years?)... so I probably prefer to fetch my old and dusty Thinkpad which also has Win 10. I'm away over Pentecost though, hope I'll find time to test this afterwards.

**Comment by tlienart** [comment]
Haven't heard back from this in a while so will  cross  my fingers and hope this was  an outlier. Re-comment here if you'd like this to  be re-opened.
