### ISSUE TITLE
Get CI working

### ISSUE THREAD

**Issue by tlienart** [asprionj/LiveServer.jl#8]
I'll work on tests eventually but it'd be good if you could go to 

* https://travis-ci.org/ log in with your github account and tick this package
* https://codecov.io same story

not urgent, just opening the issue so we don't lose that in the ocean of emails (I know I'm responsible for 90% of that).

**Comment by asprionj** [comment]
Done. What do I need to do with the `CODECOV_TOKEN`? I just added it as an env. var. on Travis...?
