### ISSUE TITLE
infinite loop when use for Yao.jl documentation

### ISSUE THREAD

**Issue by Roger-luo** [asprionj/LiveServer.jl#86]
It seems to be caused by some error? I used this to serve Yao's doc: https://github.com/QuantumBFS/Yao.jl on master branch, and it seems to keep re-run the entire building script without actually editing the file.

**Comment by tlienart** [comment]
Hmm I'm sorry about this! Several questions:

- which version of LiveServer are you on?
- did this just start happening recently?

I just  did a test run on one of my own packages with the latest version of LiveServer and it worked fine, I will try on a fork of Yao and see.

**Comment by tlienart** [comment]
this is addressed in  #85, closing here
