### ISSUE TITLE
Making the watcher an argument to `serve`

### ISSUE THREAD

**Issue by tlienart** [asprionj/LiveServer.jl#9]
I'm thinking that the logic `watcher!` (using the terminology in my PR but basically the stuff where you look at whether files have changed) could be passed to `serve` which should just serve as a vector to generates browser refreshes.

That way JuDoc (or anything else) could implement its own logic for watching files, possibly doing more stuff along the way, and ping the websockets via serve.

It needs a bit of thinking as to how the API can be exposed properly to an external package but I think it shouldn't be too hard and for JuDoc it'd be great (and would kill the problem that you mentioned some time ago of watching the files twice).

**Comment by asprionj** [comment]
Like the idea! Basically, a watcher passed to the live server just needs to inform the server about any changed file. And in the other direction, it may get, from the server, the information about files that have been served so far. If it uses this information, it can be more efficient (watch less files), if it does not, it's completely autonomous. I guess this makes the live server very flexible for different use cases.

**Comment by tlienart** [comment]
this is what you're doing now right? so we can close?

**Comment by asprionj** [comment]
Yep, discussion about it belongs to PR #14 now.
