### ISSUE TITLE
hope this is closer to http.server 

### ISSUE THREAD

**Issue by zsz00** [asprionj/LiveServer.jl#91]
hope this is closer to python http.server :
1. It can work  in any folder. and do not generate other files such as css/index.html in the folder.
2. support for remote access, http://0.0.0.0:8080 . 

Thank you!!

**Comment by tlienart** [comment]
Hello, sorry I do not understand. Is this a feature request? LiveServer works in any folder and does not generate files.
Can you also explain your second point? you can  currently specify the `8080`  port if you want.

**Comment by zsz00** [comment]
1.  such as :
julia> serve(port=8080, dir="/home/aa/test", verbose=true)    
![image](https://user-images.githubusercontent.com/12711073/69912921-901b8400-146b-11ea-9c30-330ec07dbbf8.png)
 
2.  LiveServer is  http://localhost:8080, not http://0.0.0.0:8080, so do not remote access.

**Comment by tlienart** [comment]
I apologise, I still have trouble understanding what you would like. 

1. If you have a folder `someFolder` with a valid file `index.html`, doing `serve()` will allow you to render that page etc. If there are additional files like CSS etc, it will use them, it  does  not generate anything.

Here's a simple example

```julia
julia> mkdir("someFolder")
"someFolder"

julia> cd("someFolder")

julia> write("index.html", """
       <!DOCTYPE html>
       <html>
       <body>

       <h1>My First Heading</h1>

       <p>My first paragraph.</p>

       </body>
       </html>
       """)
102

julia> using LiveServer

julia> serve()
✓ LiveServer listening on http://localhost:8000/ ...
  (use CTRL+C to shut down)
```

<img width="382" alt="Screen Shot 2019-12-01 at 11 55 41" src="https://user-images.githubusercontent.com/10897531/69913594-8e34cf00-1431-11ea-9fd0-4b204973fcb3.png">

2. Could you please clarify what's the use case you want? yes indeed it's localhost.

**Comment by zsz00** [comment]
1. If you have a folder someFolder with a valid file (aa.png, graph_1.py, but not index.html), doing serve() will allow you to render that page etc.  
i want this:
![image](https://user-images.githubusercontent.com/12711073/69914778-24451580-1483-11ea-9483-dd53e057f6bb.png)

2. I want access the remote folder on 10.42.64.84, I local host is 10.42.3.1.

**Comment by tlienart** [comment]
Ok  this is now clearer thank you.

The first point is trivial to accomplish (basically amounts to writing a temporary `index.html` file with a list matching `dir` and serving that).

The second point is potentially not hard but I can't really afford to  look  into  it. PRs would be very welcome, I would suspect it would require investing how to change this line https://github.com/asprionj/LiveServer.jl/blob/af80d3a493e4ca3f5e8c979a9ce73210be917dd8/src/server.jl#L226 for something that doesn't listen on localhost but on  a given address.

**Comment by tlienart** [comment]
Edit: yes so `Sockets` can take an address so it should be reasonably straighforward
