### ISSUE TITLE
servedocs() with subfolder not named docs?

### ISSUE THREAD

**Issue by cserteGT3** [asprionj/LiveServer.jl#99]
I've started working on a standalone documentation site with Documenter.jl and named the usually "docs" folder as "site". I've tried to use the `servedocs` function, but it expects a "docs" folder (as stated clearly in the documentation).
I started to put together a PR that adds a keyword to `servedocs` to change the name of the source folder, but now that I looked into the code, I see that the foldername is hardcoded in many places. So before I "rewrite" all the related functions, I though I ask if it is a desired functionality or should I search for a workaround?

**Comment by tlienart** [comment]
Well it's desired by you :) 

if you add a kwarg `foldername="docs"` to `servedocs`, `scan_docs!`, and `servedocs_callback!`  it should be good to go. If you can extend the tests so that it's tested that'd be great too.

Thanks Tamás!

**Comment by cserteGT3** [comment]
As soon as I opened the issue, I started working on it, because in worst case, it stays in my fork ;)

Regarding to the implementation: my idea is to store in a `const FOLDERNAME = Ref{String}("docs")` variable, that is updated with the keyword and accessed in every related function (instead of passing it). Is it ok?

**Comment by tlienart** [comment]
no I'd rather you passed this as an argument please

**Comment by cserteGT3** [comment]
I've already done it [here](https://github.com/cserteGT3/LiveServer.jl/tree/cst-docfolderkw) with global const 😄. But, then I'll make with function arguments.

**Comment by tlienart** [comment]
Thanks! sorry yeah global consts should not be accessible from the outside and, generally, should be avoided (I know I'm guilty of doing both in Franklin but I try to reduce that to the strict necessary)

btw you are missed, now going to the other side, the Documenter land, with no new commands and clever table inputs 😢

**Comment by cserteGT3** [comment]
> Thanks! sorry yeah global consts should not be accessible from the outside and, generally, should be avoided (I know I'm guilty of doing both in Franklin but I try to reduce that to the strict necessary)

No worries, I only thought about performance, which should be ok with const, and didn't think of other design decisions.

> btw you are missed, now going to the other side, the Documenter land, with no new commands and clever table inputs 😢

😢  I've chosen Documenter, because it's easy to generate a pdf, which is needed in this case. (My personal page stays Franklin with PlotlyJS 😉 )

**Comment by cserteGT3** [comment]
Implemented in #100
